/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caesar_auto_MainActivity */

#include <string>
#include <android/log.h>

#define LOG_TAG    "Main = "
#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGD(...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

#ifndef _Included_com_caesar_auto_MainActivity
#define _Included_com_caesar_auto_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caesar_auto_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_caesar_auto_MainActivity_stringFromJNI
  (JNIEnv *, jobject){
    LOGD("stringFromJNI");
    LOGE("stringFromJNI");
    LOGI("stringFromJNI");
}

/*
 * Class:     com_caesar_auto_MainActivity
 * Method:    intFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_caesar_auto_MainActivity_intFromJNI
  (JNIEnv *, jobject){
    LOGD("intFromJNI");
    LOGE("intFromJNI");
    LOGI("intFromJNI");
}

/*
 * Class:     com_caesar_auto_MainActivity
 * Method:    LongFromJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caesar_auto_MainActivity_LongFromJNI
  (JNIEnv *, jobject){
    LOGD("LongFromJNI");
    LOGE("LongFromJNI");
    LOGI("LongFromJNI");
}

/*
 * Class:     com_caesar_auto_MainActivity
 * Method:    aCharFromJNI
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_caesar_auto_MainActivity_aCharFromJNI
  (JNIEnv *, jobject){
    LOGD("aCharFromJNI");
    LOGE("aCharFromJNI");
    LOGI("aCharFromJNI");
}

#ifdef __cplusplus
}
#endif
#endif
